---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/spartidarh/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-spartida-testing
